### ISSUE TITLE
Errors installing/importing in python3.6

### ISSUE THREAD

**Issue by btengels** [randall-romero/CompEcon-python#1]
Hi Randall,

Thanks for putting this project together. I'm using python3.6 and attempting a plain install  `python setup.py install` and getting the following error:

    File "build/bdist.macosx-10.5-x86_64/egg/compecon/quadrature.py", line 9
        def __init__(self, dist, *args):
                                       ^
    SyntaxError: unexpected EOF while parsing

Weird as it is, it doesn't break the install. When I try to `from compecon import Basis` I get this error:

    In [2]: from compecon import Basis
      File "/Users/btengels/Dropbox/Econ/VCS_Tengelsen/Book code/CompEcon-python-master/compecon/demos/setup.py", line 106
        fname = name + f'--{n+1:02d}.pdf'
                                        ^
    SyntaxError: invalid syntax

Is this familiar at all?

**Comment by randall-romero** [comment]
Hi Ben,

Thank you for reporting these two issues. 
1) quadrature.py file: you can safely delete it of comment out all of its content. I shouldn't have included it in the repository yet (it was just work in progress, to make an object-oriented version of the functions in the quad.py file. Sorry about that.

2) demos/setup.py file: I could not figure this out; in my PC it's working fine. Are you sure you are using Python 3.6? If not, the problem would be with the f-string, which is a new feature in 3.6. I'll try again to see if I can spot the cause of the problem.
